Updated

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,41 +1,81 @@
 pipeline{
-    agent {label 'frontend'}
+    agent any
     environment {
-
-        APP_SERVER = "172.31.40.90"
-        DEPLOY_DIR = "/var/www/html"
+        IMAGE_NAME = "rutuja2812/frontend"
+        IMAGE_TAG = "${BUILD_NUMBER}"
+        APP_SERVER = "15.206.163.8"
+       
     }
     stages{
         
-        stage('Pre Build Actions'){
+        stage('checkout'){
             steps{
-                sh 'npm install'
+                git branch: 'main',
+                url: 'https://github.com/RBSanap/Jenkins-WebApp.git'
+               
             }
         }
-        stage('Build'){
+        stage('Build Docker Image'){
             steps{
-                sh 'npm run build'
+                sh '''
+                docker build -f docker/dockerfile -t ${IMAGE_NAME}:${IMAGE_TAG} .
+                '''
             }
         }
-        stage('Post Build Actions'){
+        stage('docker login'){
             steps {
-
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'DockerCred',
+                        usernameVariable: 'DOCKER_USER',
+                        passwordVariable: 'DOCKER_PASS'
+                    
+                )
+                ]) {
+                    sh '''
+                    echo $DOCKER_PASS | docker login \
+                    -u $DOCKER_USER \
+                    --password-stdin
+                    '''
+                }
+            }
+        }
+        stage('Push Image'){    
+        steps{
                 sh """
-
-                echo 'Cleaning old files on app server'
-
-                ssh jenkins@${APP_SERVER} 'rm -rf ${DEPLOY_DIR}/*'
-
-                echo 'Copying frontend build'
-
-                scp -r dist/* jenkins@${APP_SERVER}:${DEPLOY_DIR}/
-
-                echo 'Restarting nginx'
-
-                ssh jenkins@${APP_SERVER} 'sudo systemctl restart nginx'
-
+                docker push ${IMAGE_NAME}:${IMAGE_TAG}
+                docker tag
+                ${IMAGE_NAME}:${IMAGE_TAG} \
+                ${IMAGE_NAME}:latest
+                docker push ${IMAGE_NAME}:latest
+                '''
+            }
+        }
+        stage('Deploy to App Server'){
+            steps{
+                sh """
+                ssh ubuntu@APP_SERVER '
+                docker pull ${IMAGE_NAME}:latest
+                docker stop frontend || true
+                docker rm frontend || true
+                docker run -d \
+                --name forntend \
+                -p 80:80 \
+                ${IMAGE_NAME}:latest
+                '
                 """
             }
+        }
+    }
+    post{
+        success{
+            echo "Deployment Successful"
+        }
+        failure{   
+            echo "Deployment Failed"
+
+        
+        
         }
     }
 }
